USE master
GO
IF DB_ID('dcBooking') IS NOT NULL
	DROP DATABASE dcBooking
GO
CREATE DATABASE dcBooking
GO
USE dcBooking
GO

CREATE TABLE VAITRO (
	MAVT CHAR(2) PRIMARY KEY,
	TENVT NVARCHAR(13)
);
CREATE TABLE TAIKHOAN (
	MATK CHAR(8) PRIMARY KEY,
	SDT VARCHAR(10) NOT NULL UNIQUE,
	MK VARCHAR(64) NOT NULL,
	MAVT CHAR(2) NOT NULL,
	STATUS BIT NOT NULL DEFAULT 1

	CONSTRAINT FK_TK_VT
	FOREIGN KEY (MAVT)
	REFERENCES VAITRO(MAVT)
);

CREATE TABLE QUANTRIVIEN (
	MATK CHAR(8) NOT NULL,
    MAQTV INT IDENTITY(0, 1) PRIMARY KEY,
    HOTEN NVARCHAR(32) NOT NULL

	CONSTRAINT FK_QTV_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE NHASI (
	MATK CHAR(8) NOT NULL,
    MANS INT IDENTITY(0, 1) PRIMARY KEY,
    HOTEN NVARCHAR(32) NOT NULL

	CONSTRAINT FK_NS_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE NHANVIEN (
	MATK CHAR(8) NOT NULL,
    MANV INT IDENTITY(0, 1) PRIMARY KEY,
    HOTEN NVARCHAR(32) NOT NULL

	CONSTRAINT FK_NV_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE KHACHHANG (
	MATK CHAR(8) NOT NULL,
    MAKH INT IDENTITY(0, 1) PRIMARY KEY,
    HOTEN NVARCHAR(32) NOT NULL,
    NGAYSINH DATE NOT NULL,
    DIACHI NVARCHAR(128) NOT NULL

	CONSTRAINT FK_KH_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE DICHVU (
	MADV INT IDENTITY(0, 1) PRIMARY KEY,
	TENDV NVARCHAR(32),
	PHIKHAM FLOAT NOT NULL
);
CREATE TABLE THUOC (
	MATH INT IDENTITY(0, 1) PRIMARY KEY,
	TENTHUOC NVARCHAR(32) NOT NULL,
	DONVITINH NVARCHAR(8) NOT NULL,
	CHIDINH NVARCHAR(32) NOT NULL,
	NGAYHETHAN DATE NOT NULL,
	SLKHO INT NOT NULL,
	DONGIA FLOAT NOT NULL
);

CREATE TABLE LICHSUKHAM (
	MALSK INT IDENTITY(0, 1) PRIMARY KEY,
	MAKH INT NOT NULL,
	MANS INT NOT NULL,
	THOIGIAN DATETIME DEFAULT GETDATE()

	CONSTRAINT FK_LSK_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG(MAKH),
	
	CONSTRAINT FK_LSK_NS
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);
CREATE TABLE DICHVUSD (
	MALSK INT,
	MADV INT,
	THANHTOAN BIT NOT NULL

	CONSTRAINT PK_DVSD
	PRIMARY KEY (MALSK, MADV),

	CONSTRAINT FP_DVSC_DV
	FOREIGN KEY (MADV)
	REFERENCES DICHVU(MADV),

	CONSTRAINT FP_DVSC_LSK
	FOREIGN KEY (MALSK)
	REFERENCES LICHSUKHAM(MALSK)
);
CREATE TABLE DONTHUOC (
	MALSK INT,
	MATH INT,
	SOLUONG INT NOT NULL

	CONSTRAINT PK_DT
	PRIMARY KEY (MALSK, MATH),

	CONSTRAINT FK_DT_TH
	FOREIGN KEY (MATH)
	REFERENCES THUOC(MATH),

	CONSTRAINT FP_DT_LSK
	FOREIGN KEY (MALSK)
	REFERENCES LICHSUKHAM(MALSK)
);

CREATE TABLE LICHHEN (
	MALH INT IDENTITY(0, 1) PRIMARY KEY,
	THOIGIAN DATETIME NOT NULL,
	MAKH INT NOT NULL,
	MANS INT NOT NULL

	CONSTRAINT PK_LH_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG(MAKH),
	
	CONSTRAINT PK_LH_NS
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);
CREATE TABLE LICHRANH (
	MALR INT IDENTITY(0, 1) PRIMARY KEY,
	MANS INT NOT NULL,
	THOIGIAN DATETIME NOT NULL
	
	CONSTRAINT FK_LR_NS
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);

USE master
GO