USE master
GO
IF DB_ID('dcBooking') IS NOT NULL
	DROP DATABASE dcBooking
GO
CREATE DATABASE dcBooking
GO
USE dcBooking
GO

CREATE TABLE TAIKHOAN (
	MATK CHAR(8) NOT NULL PRIMARY KEY,
	SDT VARCHAR(10) NOT NULL UNIQUE,
	MK VARCHAR(64) NOT NULL,
	LOAITK INT NOT NULL
);

CREATE TABLE KHACHHANG (
	MATK CHAR(8) NOT NULL,
    MAKH CHAR(8) NOT NULL PRIMARY KEY,
    HOTEN NVARCHAR(32) NOT NULL,
    NGAYSINH DATE NOT NULL,
    DIACHI NVARCHAR(128) NOT NULL

	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE QUANTRIVIEN (
	MATK CHAR(8) NOT NULL,
    MAQTV CHAR(8) NOT NULL PRIMARY KEY,
    HOTEN NVARCHAR(32) NOT NULL

	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE NHASI (
	MATK CHAR(8) NOT NULL,
    MANS CHAR(8) NOT NULL PRIMARY KEY,
    HOTEN NVARCHAR(32) NOT NULL

	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE NHANVIEN (
	MATK CHAR(8) NOT NULL,
    MANV CHAR(8) NOT NULL PRIMARY KEY,
    HOTEN NVARCHAR(32) NOT NULL

	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE DICHVU (
	MADV CHAR(8) NOT NULL PRIMARY KEY,
	TENDV NVARCHAR(32) NOT NULL,
	PHIKHAM INT NOT NULL
);
CREATE TABLE GOIDV (
	MAGOI CHAR(16) NOT NULL PRIMARY KEY,
	MADV CHAR(8) NOT NULL

	FOREIGN KEY (MADV)
	REFERENCES DICHVU(MADV)
);

CREATE TABLE THUOC(
	MAT CHAR(8) NOT NULL PRIMARY KEY,
	TENTHUOC NVARCHAR(32) NOT NULL,
	DONVITINH NVARCHAR(8) NOT NULL,
	CHIDINH NVARCHAR(32) NOT NULL,
	NGAYHETHAN DATE NOT NULL,
	SLKHO INT NOT NULL,
	DONGIA INT NOT NULL
);
CREATE TABLE DONTHUOC(
	MADT CHAR(16) NOT NULL PRIMARY KEY,
	MAT CHAR(8) NOT NULL,
	SOLUONG INT NOT NULL

	FOREIGN KEY (MAT)
	REFERENCES THUOC(MAT)
);
CREATE TABLE HOADON(
	MAHD CHAR(16) NOT NULL PRIMARY KEY,
	MAGOI CHAR(16) NOT NULL,
	MADT CHAR(16) NOT NULL,
	THOIGIAN DATETIME NOT NULL

	FOREIGN KEY (MAGOI)
	REFERENCES GOIDV(MAGOI),
	
	FOREIGN KEY (MADT)
	REFERENCES DONTHUOC(MADT)
);

CREATE TABLE LICHSUKHAM (
	MALSK CHAR(16) NOT NULL PRIMARY KEY,
	MAKH CHAR(8) NOT NULL,
	MANS CHAR(8) NOT NULL,
	THOIGIAN DATETIME NOT NULL,
	MAGOI CHAR(16) NOT NULL,
	MADT CHAR(16) NOT NULL

	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG(MAKH),
	
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS),

	FOREIGN KEY (MAGOI)
	REFERENCES GOIDV(MAGOI),

	FOREIGN KEY (MADT)
	REFERENCES DONTHUOC(MADT)
);
CREATE TABLE LICHHEN(
	MALH CHAR(16) NOT NULL PRIMARY KEY,
	THOIGIAN DATETIME NOT NULL,
	MAKH CHAR(8) NOT NULL,
	MANS CHAR(8) NOT NULL

	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG(MAKH),
	
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);
CREATE TABLE LICHRANH(
	MALR CHAR(16) PRIMARY KEY,
	MANS CHAR(8) NOT NULL,
	THOIGIAN DATETIME NOT NULL
	
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);