USE dcBooking
GO

CREATE ROLE QUANTRI_ROLE

GRANT SELECT, INSERT, UPDATE ON VAITRO TO QUANTRI
GRANT SELECT, INSERT, UPDATE ON TAIKHOAN TO QUANTRI
GRANT SELECT, INSERT, UPDATE ON QUANTRIVIEN TO QUANTRI
GRANT SELECT, INSERT, UPDATE ON NHASI TO QUANTRI
GRANT SELECT, INSERT, UPDATE ON NHANVIEN TO QUANTRI
GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO QUANTRI
GRANT SELECT, INSERT, UPDATE ON DICHVU TO QUANTRI
GRANT SELECT, INSERT, UPDATE ON THUOC TO QUANTRI

GRANT SELECT ON LICHSUKHAM TO QUANTRI
GRANT SELECT ON DICHVUSD TO QUANTRI
GRANT SELECT ON DONTHUOC TO QUANTRI
GRANT SELECT ON LICHHEN TO QUANTRI
GRANT SELECT ON LICHRANH TO QUANTRI


CREATE ROLE NHASI_ROLE




CREATE ROLE NHANVIEN_ROLE


CREATE ROLE KHACHHANG_ROLE