USE dcBooking
GO

CREATE ROLE QUANTRI_ROLE

GRANT SELECT, INSERT, UPDATE, DELETE ON VAITRO TO QUANTRI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON TAIKHOAN TO QUANTRI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON NHASI TO QUANTRI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON NHANVIEN TO QUANTRI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON DICHVU TO QUANTRI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON THUOC TO QUANTRI_ROLE
GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO QUANTRI_ROLE
GRANT SELECT ON QUANTRIVIEN TO QUANTRI_ROLE
GRANT SELECT ON LICHSUKHAM TO QUANTRI_ROLE
GRANT SELECT ON DICHVUSD TO QUANTRI_ROLE
GRANT SELECT ON DONTHUOC TO QUANTRI_ROLE
GRANT SELECT ON LICHHEN TO QUANTRI_ROLE
GRANT SELECT ON LICHLAMVIEC TO QUANTRI_ROLE


CREATE ROLE NHASI_ROLE

GRANT SELECT, INSERT, UPDATE, DELETE ON DICHVUSD TO NHASI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON DONTHUOC TO NHASI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON LICHLAMVIEC TO NHASI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON LICHSUKHAM TO NHASI_ROLE
GRANT SELECT, UPDATE ON TAIKHOAN TO NHASI_ROLE
GRANT SELECT, UPDATE ON NHASI TO NHASI_ROLE
GRANT SELECT ON KHACHHANG TO NHASI_ROLE
GRANT SELECT ON DICHVU TO NHASI_ROLE
GRANT SELECT ON THUOC TO NHASI_ROLE
GRANT SELECT ON LICHHEN TO NHASI_ROLE


CREATE ROLE NHANVIEN_ROLE

GRANT SELECT, INSERT, UPDATE, DELETE LICHHEN TO NHANVIEN_ROLE
GRANT SELECT, INSERT, UPDATE ON TAIKHOAN TO NHANVIEN_ROLE
GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO NHANVIEN_ROLE
GRANT SELECT, UPDATE ON NHANVIEN TO NHANVIEN_ROLE
GRANT SELECT ON NHASHI TO NHANVIEN_ROLE
GRANT SELECT ON LICHSUKHAM TO KHACHHANG_ROLE
GRANT SELECT ON DICHVU TO KHACHHANG
GRANT SELECT ON THUOC TO KHACHHANG
GRANT SELECT ON DICHVUSD TO KHACHHANG
GRANT SELECT ON DONTHUOC TO KHACHHANG


CREATE ROLE KHACHHANG_ROLE

GRANT SELECT, INSERT, UPDATE, DELETE ON LICHHEN TO KHACHHANGROLE
GRANT SELECT, UPDATE ON TAIKHOAN TO KHACHHANG_ROLE
GRANT SELECT, UPDATE ON KHACHHANG TO KHACHHANG_ROLE
GRANT SELECT ON NHASHI TO NHANVIEN_ROLE
GRANT SELECT ON LICHSUKHAM TO KHACHHANG_ROLE
GRANT SELECT ON DICHVU TO KHACHHANG
GRANT SELECT ON THUOC TO KHACHHANG
GRANT SELECT ON DICHVUSD TO KHACHHANG
GRANT SELECT ON DONTHUOC TO KHACHHANG