CREATE DATABASE dcBooking
GO
USE dcBooking
GO

EXEC sp_addtype 'PHONE', 'VARCHAR(10)', 'NOT NULL'
EXEC sp_addtype 'XSTEXT', 'NVARCHAR(16)', 'NOT NULL'
EXEC sp_addtype 'STEXT', 'NVARCHAR(32)', 'NOT NULL'
EXEC sp_addtype 'MTEXT', 'NVARCHAR(64)', 'NOT NULL'
EXEC sp_addtype 'LTEXT', 'NVARCHAR(128)'
GO

CREATE TABLE VAITRO (
	MAVT INT IDENTITY PRIMARY KEY,
	TENVT XSTEXT
);
CREATE TABLE TAIKHOAN (
	MATK INT IDENTITY PRIMARY KEY,
	SDT PHONE UNIQUE,
	MK MTEXT,
	MAVT INT,
	HOATDONG BIT NOT NULL DEFAULT 1

	CONSTRAINT FK_TK_VT
	FOREIGN KEY (MAVT)
	REFERENCES VAITRO(MAVT)
);

CREATE TABLE QUANTRIVIEN (
	MATK INT NOT NULL,
    MAQTV INT IDENTITY PRIMARY KEY,
    HOTEN STEXT

	CONSTRAINT FK_QTV_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE NHASI (
	MATK INT NOT NULL,
    MANS INT IDENTITY PRIMARY KEY,
    HOTEN STEXT

	CONSTRAINT FK_NS_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE NHANVIEN (
	MATK INT NOT NULL,
    MANV INT IDENTITY PRIMARY KEY,
    HOTEN STEXT

	CONSTRAINT FK_NV_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE KHACHHANG (
	MATK INT NOT NULL,
    MAKH INT IDENTITY PRIMARY KEY,
    HOTEN STEXT,
    NGAYSINH DATE NOT NULL CHECK (NGAYSINH <= GETDATE()),
    DIACHI LTEXT

	CONSTRAINT FK_KH_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE DICHVU (
	MADV INT IDENTITY PRIMARY KEY,
	TENDV STEXT,
	PHIKHAM FLOAT NOT NULL
);
CREATE TABLE THUOC (
	MATH INT IDENTITY PRIMARY KEY,
	TENTHUOC STEXT,
	DONVITINH XSTEXT,
	CHIDINH STEXT,
	NGAYHETHAN DATE NOT NULL,
	SLKHO INT NOT NULL,
	DONGIA FLOAT NOT NULL
);

CREATE TABLE LICHSUKHAM (
	MALSK INT IDENTITY PRIMARY KEY,
	MAKH INT NOT NULL,
	MANS INT NOT NULL,
	THOIGIAN DATETIME NOT NULL DEFAULT GETDATE(),
	GHICHU LTEXT,
	THANHTOAN BIT NOT NULL DEFAULT 0

	CONSTRAINT FK_LSK_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG(MAKH),
	
	CONSTRAINT FK_LSK_NS
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);
CREATE TABLE DICHVUSD (
	MALSK INT,
	MADV INT

	CONSTRAINT PK_DVSD
	PRIMARY KEY (MALSK, MADV),

	CONSTRAINT FK_DVSC_DV
	FOREIGN KEY (MADV)
	REFERENCES DICHVU(MADV),

	CONSTRAINT FK_DVSC_LSK
	FOREIGN KEY (MALSK)
	REFERENCES LICHSUKHAM(MALSK)
);
CREATE TABLE DONTHUOC (
	MALSK INT,
	MATH INT,
	SOLUONG INT NOT NULL,
	GHICHU LTEXT

	CONSTRAINT PK_DT
	PRIMARY KEY (MALSK, MATH),

	CONSTRAINT FK_DT_TH
	FOREIGN KEY (MATH)
	REFERENCES THUOC(MATH),

	CONSTRAINT FK_DT_LSK
	FOREIGN KEY (MALSK)
	REFERENCES LICHSUKHAM(MALSK)
);

CREATE TABLE LICHHEN (
	MALH INT IDENTITY PRIMARY KEY,
	MAKH INT NOT NULL,
	MANS INT NOT NULL,
	THOIGIAN DATETIME NOT NULL

	CONSTRAINT FK_LH_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG(MAKH),
	
	CONSTRAINT FK_LH_NS
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);
CREATE TABLE LICHLAMVIEC (
	MALV INT IDENTITY PRIMARY KEY,
	MANS INT NOT NULL,
	BATDAU DATETIME NOT NULL,
	KETTHUC DATETIME NOT NULL
	
	CONSTRAINT FK_LR_NS
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);
ALTER TABLE LICHLAMVIEC
ADD CONSTRAINT CK_KT_BD
CHECK (KETTHUC > BATDAU);