USE master
GO
IF DB_ID('dcBooking') IS NOT NULL
	DROP DATABASE dcBooking
GO
CREATE DATABASE dcBooking
GO
USE dcBooking
GO

EXEC sp_addtype 'BNN', 'BIT', 'NOT NULL'
EXEC sp_addtype 'INN', 'INT', 'NOT NULL'
EXEC sp_addtype 'FNN', 'FLOAT', 'NOT NULL'
EXEC sp_addtype 'DNN', 'DATE', 'NOT NULL'
EXEC sp_addtype 'DTNN', 'DATETIME', 'NOT NULL'

EXEC sp_addtype 'PHONE', 'VARCHAR(10)', 'NOT NULL'
EXEC sp_addtype 'XXSTEXT', 'NVARCHAR(2)', 'NOT NULL'
EXEC sp_addtype 'XSTEXT', 'NVARCHAR(16)', 'NOT NULL'
EXEC sp_addtype 'STEXT', 'NVARCHAR(32)', 'NOT NULL'
EXEC sp_addtype 'MTEXT', 'NVARCHAR(64)', 'NOT NULL'
EXEC sp_addtype 'LTEXT', 'NVARCHAR(128)'
EXEC sp_addtype 'XLTEXT', 'NVARCHAR(256)'

CREATE TABLE VAITRO (
	MAVT XXSTEXT PRIMARY KEY,
	TENVT XSTEXT
);
CREATE TABLE TAIKHOAN (
	MATK INT IDENTITY PRIMARY KEY,
	SDT PHONE UNIQUE,
	MK MTEXT,
	MAVT XXSTEXT,
	HOATDONG BNN DEFAULT 1

	CONSTRAINT FK_TK_VT
	FOREIGN KEY (MAVT)
	REFERENCES VAITRO(MAVT)
);

CREATE TABLE QUANTRIVIEN (
	MATK INN,
    MAQTV INT IDENTITY PRIMARY KEY,
    HOTEN STEXT

	CONSTRAINT FK_QTV_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE NHASI (
	MATK INN,
    MANS INT IDENTITY PRIMARY KEY,
    HOTEN STEXT

	CONSTRAINT FK_NS_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE NHANVIEN (
	MATK INN,
    MANV INT IDENTITY PRIMARY KEY,
    HOTEN STEXT

	CONSTRAINT FK_NV_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);
CREATE TABLE KHACHHANG (
	MATK INN,
    MAKH INT IDENTITY PRIMARY KEY,
    HOTEN STEXT,
    NGAYSINH DNN CHECK (NGAYSINH <= GETDATE()),
    DIACHI LTEXT

	CONSTRAINT FK_KH_TK
	FOREIGN KEY (MATK)
	REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE DICHVU (
	MADV INT IDENTITY PRIMARY KEY,
	TENDV STEXT,
	PHIKHAM FNN
);
CREATE TABLE THUOC (
	MATH INT IDENTITY PRIMARY KEY,
	TENTHUOC STEXT,
	DONVITINH XSTEXT,
	CHIDINH STEXT,
	NGAYHETHAN DNN,
	SLKHO INN,
	DONGIA FNN
);

CREATE TABLE LICHSUKHAM (
	MALSK INT IDENTITY PRIMARY KEY,
	MAKH INN,
	MANS INN,
	THOIGIAN DTNN DEFAULT GETDATE(),
	GHICHU XLTEXT

	CONSTRAINT FK_LSK_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG(MAKH),
	
	CONSTRAINT FK_LSK_NS
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);
CREATE TABLE DICHVUSD (
	MALSK INT,
	MADV INT,
	THANHTOAN BNN DEFAULT 0

	CONSTRAINT PK_DVSD
	PRIMARY KEY (MALSK, MADV),

	CONSTRAINT FP_DVSC_DV
	FOREIGN KEY (MADV)
	REFERENCES DICHVU(MADV),

	CONSTRAINT FP_DVSC_LSK
	FOREIGN KEY (MALSK)
	REFERENCES LICHSUKHAM(MALSK)
);
CREATE TABLE DONTHUOC (
	MALSK INT,
	MATH INT,
	SOLUONG INN,
	GHICHU LTEXT

	CONSTRAINT PK_DT
	PRIMARY KEY (MALSK, MATH),

	CONSTRAINT FK_DT_TH
	FOREIGN KEY (MATH)
	REFERENCES THUOC(MATH),

	CONSTRAINT FP_DT_LSK
	FOREIGN KEY (MALSK)
	REFERENCES LICHSUKHAM(MALSK)
);

CREATE TABLE LICHHEN (
	MALH INT IDENTITY PRIMARY KEY,
	THOIGIAN DTNN,
	MAKH INN,
	MANS INN

	CONSTRAINT PK_LH_KH
	FOREIGN KEY (MAKH)
	REFERENCES KHACHHANG(MAKH),
	
	CONSTRAINT PK_LH_NS
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);
CREATE TABLE LICHLAMVIEC (
	MALV INT IDENTITY PRIMARY KEY,
	MANS INN,
	THOIGIAN DTNN CHECK (THOIGIAN >= GETDATE())
	
	CONSTRAINT FK_LR_NS
	FOREIGN KEY (MANS)
	REFERENCES NHASI(MANS)
);