USE dcBooking
GO

CREATE ROLE NHASI_ROLE

GRANT SELECT, INSERT, UPDATE, DELETE ON DICHVUSD TO NHASI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON DONTHUOC TO NHASI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON LICHLAMVIEC TO NHASI_ROLE
GRANT SELECT, INSERT, UPDATE, DELETE ON LICHSUKHAM TO NHASI_ROLE
GRANT SELECT, UPDATE ON TAIKHOAN TO NHASI_ROLE
GRANT SELECT, UPDATE ON NHASI TO NHASI_ROLE
GRANT SELECT ON KHACHHANG TO NHASI_ROLE
GRANT SELECT ON DICHVU TO NHASI_ROLE
GRANT SELECT ON THUOC TO NHASI_ROLE
GRANT SELECT ON LICHHEN TO NHASI_ROLE
GO

CREATE ROLE NHANVIEN_ROLE

GRANT SELECT, INSERT, UPDATE, DELETE ON LICHHEN TO NHANVIEN_ROLE
GRANT SELECT, INSERT, UPDATE ON TAIKHOAN TO NHANVIEN_ROLE
GRANT SELECT, INSERT, UPDATE ON KHACHHANG TO NHANVIEN_ROLE
GRANT SELECT, UPDATE ON NHANVIEN TO NHANVIEN_ROLE
GRANT SELECT ON NHASI TO NHANVIEN_ROLE
GRANT SELECT ON LICHSUKHAM TO NHANVIEN_ROLE
GRANT SELECT ON DICHVU TO NHANVIEN_ROLE
GRANT SELECT ON THUOC TO NHANVIEN_ROLE
GRANT SELECT ON DICHVUSD TO NHANVIEN_ROLE
GRANT SELECT ON DONTHUOC TO NHANVIEN_ROLE
GO

CREATE ROLE KHACHHANG_ROLE

GRANT SELECT, INSERT, UPDATE, DELETE ON LICHHEN TO KHACHHANG_ROLE
GRANT SELECT, UPDATE ON TAIKHOAN TO KHACHHANG_ROLE
GRANT SELECT, UPDATE ON KHACHHANG TO KHACHHANG_ROLE
GRANT SELECT ON NHASI TO NHANVIEN_ROLE
GRANT SELECT ON LICHSUKHAM TO KHACHHANG_ROLE
GRANT SELECT ON DICHVU TO KHACHHANG_ROLE
GRANT SELECT ON THUOC TO KHACHHANG_ROLE
GRANT SELECT ON DICHVUSD TO KHACHHANG_ROLE
GRANT SELECT ON DONTHUOC TO KHACHHANG_ROLE
GO

EXEC sp_addlogin dcBooking_QT, '123', dcBooking
EXEC sp_addlogin dcBooking_NS, '123', dcBooking
EXEC sp_addlogin dcBooking_NV, '123', dcBooking
EXEC sp_addlogin dcBooking_KH, '123', dcBooking
GO

CREATE USER dcBooking_NS1 FOR LOGIN dcBooking_NS
CREATE USER dcBooking_NV1 FOR LOGIN dcBooking_NV
CREATE USER dcBooking_KH1 FOR LOGIN dcBooking_KH
GO

EXEC sp_addsrvrolemember dcBooking_QT, sysadmin
EXEC sp_addrolemember NHASI_ROLE, dcBooking_NS1
EXEC sp_addrolemember NHANVIEN_ROLE, dcBooking_NV1
EXEC sp_addrolemember KHACHHANG_ROLE, dcBooking_KH1
GO