USE dcBooking
GO

CREATE TYPE DVSD AS TABLE (
    MADV INT NOT NULL UNIQUE
)
GO
CREATE TYPE THSD AS TABLE (
    MATH INT NOT NULL UNIQUE,
    SOLUONG INT NOT NULL,
    GHICHU LTEXT
)
GO

DECLARE @DVSD DVSD
INSERT INTO @DVSD
VALUES
    (1), (2), (3)

DECLARE @THSD THSD
INSERT @THSD (MATH, SOLUONG, GHICHU)
VALUES
    (1, 5, N''),
    (2, 2, N'')

select * from @THSD
select * from @DVSD

EXEC sp_themLSK 1, 1, N'Tái khám', @DVSD, @THSD
GO

DROP TYPE DVSD
DROP TYPE THSD