USE dcBooking
GO

DECLARE @DVSD DVSD
INSERT INTO @DVSD
VALUES
    (1), (2), (3)

DECLARE @THSD THSD
INSERT @THSD (MATH, SOLUONG, GHICHU)
VALUES
    (1, 5, N''),
    (2, 2, N'')

EXEC sp_themLSK 1, 1, N'Tái khám', @DVSD, @THSD
GO