USE dcBooking
GO

DROP PROCEDURE sp_xemThuoc
DROP PROCEDURE sp_doiTTThuoc
GO

CREATE PROCEDURE sp_xemThuoc
    @MATH INT
AS
BEGIN TRANSACTION
    BEGIN TRY
        SELECT * FROM THUOC
        WHERE MATH = @MATH
    END TRY
    BEGIN CATCH
        PRINT N'Lỗi hệ thống'
        ROLLBACK TRANSACTION
        RETURN 0
    END CATCH
COMMIT TRANSACTION
RETURN 1
GO

CREATE PROCEDURE sp_doiTTThuoc
    @MATH INT,
    @TENTHUOC STEXT,
    @DONVITINH XSTEXT,
    @CHIDINH STEXT,
    @NGAYHETHAN DATE,
    @SLKHO INT,
    @DONGIA FLOAT
AS
BEGIN TRANSACTION
    BEGIN TRY
        UPDATE THUOC
        SET
            TENTHUOC = @TENTHUOC,
            DONVITINH = @DONVITINH,
            CHIDINH = @CHIDINH,
            NGAYHETHAN = @NGAYHETHAN,
            SLKHO = @SLKHO,
            DONGIA = @DONGIA
        WHERE MATH = @MATH
    END TRY
    BEGIN CATCH
        PRINT N'Lỗi hệ thống'
        ROLLBACK TRANSACTION
        RETURN 0
    END CATCH
COMMIT TRANSACTION
RETURN 1
GO