USE dcBooking
GO

CREATE PROCEDURE sp_xemThuoc
AS
BEGIN TRANSACTION
    BEGIN TRY
        SELECT * FROM THUOC
    END TRY
    BEGIN CATCH
        PRINT N'Lỗi hệ thống'
        ROLLBACK TRANSACTION
        RETURN 0
    END CATCH
COMMIT TRANSACTION
RETURN 1
GO

CREATE PROCEDURE sp_xoaThuoc
    @MATH INT
AS
BEGIN TRANSACTION
    BEGIN TRY
        DELETE FROM THUOC
        WHERE MATH = @MATH
    END TRY
    BEGIN CATCH
        PRINT N'Lỗi hệ thống'
        ROLLBACK TRANSACTION
        RETURN 0
    END CATCH
COMMIT TRANSACTION
RETURN 1
GO