USE dcBooking
GO

CREATE PROCEDURE sp_xemThuoc
AS
BEGIN TRANSACTION
    BEGIN TRY
        SELECT * FROM THUOC
    END TRY
    BEGIN CATCH
        PRINT N'Lỗi hệ thống'
        ROLLBACK TRANSACTION
        RETURN 0
    END CATCH
COMMIT TRANSACTION
RETURN 1
GO

CREATE PROCEDURE sp_themThuoc
    @TENTHUOC STEXT READONLY,
    @DONVITINH XSTEXT READONLY,
    @CHIDINH STEXT READONLY,
    @NGAYHETHAN DATE READONLY,
    @SLKHO INT READONLY,
    @DONGIA FLOAT READONLY
AS
BEGIN TRANSACTION
    BEGIN TRY
        INSERT INTO THUOC (TENTHUOC, DONVITINH, CHIDINH, NGAYHETHAN, SLKHO, DONGIA)
        VALUES (@TENTHUOC, @DONVITINH, @CHIDINH, @NGAYHETHAN, @SLKHO, @DONGIA)
        PRINT N'Thêm thuốc thành công'
    END TRY
    BEGIN CATCH
        PRINT N'Lỗi hệ thống'
        ROLLBACK TRANSACTION
        RETURN 0
    END CATCH
COMMIT TRANSACTION
RETURN 1
GO