USE dcBooking
GO

DECLARE @MATK INT
DECLARE @MK INT
EXEC sp_DangNhap '0916702097', '21126019', @MATK OUTPUT, @MK OUTPUT
PRINT N'Mã tài khoản: ' + CAST(@MATK AS NVARCHAR(10))
PRINT N'Mật khẩu: ' + CAST(@MK AS NVARCHAR(10))